@startuml
!include /Users/pnc12/Documents/GitHub/nowl/nowl/profiles/iof.iuml
title Thing
left to right direction
class(c1, ns2:Thing)
class(c2, ns2:entity)
subClass(c2, c1)
class(c3, ns2:continuant)
subClass(c3, c2)
class(c4, ns2:generically dependent continuant)
subClass(c4, c3)
class(c5, ns2:information content entity)
subClass(c5, c4)
class(c6, ns2:action specification)
subClass(c6, c5)
class(c7, ns2:plan specification)
subClass(c7, c5)
class(c8, ns2:algorithm)
subClass(c8, c7)
class(c9, ns2:commercial service specification)
subClass(c9, c7)
class(c10, ns2:business identification)
subClass(c10, c5)
class(c11, ns2:objective specification)
subClass(c11, c5)
class(c12, ns2:commercial service agreement)
subClass(c12, c5)
class(c13, ns2:descriptive information content entity)
subClass(c13, c5)
class(c14, ns2:design specification)
subClass(c14, c5)
class(c15, ns2:designative information content entity)
subClass(c15, c5)
class(c16, ns2:directive information content entity)
subClass(c16, c5)
class(c17, ns2:location identification)
subClass(c17, c5)
class(c18, ns2:measurement information content entity)
subClass(c18, c5)
class(c19, ns2:requirement specification)
subClass(c19, c5)
class(c20, ns2:independent continuant)
subClass(c20, c3)
class(c21, ns2:material entity)
subClass(c21, c20)
class(c22, ns2:agent)
subClass(c22, c21)
class(c23, ns2:material component)
subClass(c23, c21)
class(c24, ns2:material product)
subClass(c24, c21)
class(c25, ns2:maintainable material item)
subClass(c25, c21)
class(c26, ns2:material resource)
subClass(c26, c21)
class(c27, ns2:raw material)
subClass(c27, c21)
class(c28, ns2:fiat object part)
subClass(c28, c21)
class(c29, ns2:object aggregate)
subClass(c29, c21)
class(c30, ns2:group of agents)
subClass(c30, c29)
class(c31, ns2:organized group of agents)
subClass(c31, c30)
class(c32, ns2:business organization)
subClass(c32, c31)
class(c33, ns2:system)
subClass(c33, c29)
class(c34, ns2:engineered system)
subClass(c34, c33)
class(c35, ns2:object)
subClass(c35, c21)
class(c36, ns2:person)
subClass(c36, c35)
class(c37, ns2:material artifact)
subClass(c37, c35)
class(c38, ns2:assembly)
subClass(c38, c37)
class(c39, ns2:machine)
subClass(c39, c37)
class(c40, ns2:immaterial entity)
subClass(c40, c20)
class(c41, ns2:site)
subClass(c41, c40)
class(c42, ns2:spatial region)
subClass(c42, c40)
class(c43, ns2:two-dimensional spatial region)
subClass(c43, c42)
class(c44, ns2:zero-dimensional spatial region)
subClass(c44, c42)
class(c45, ns2:one-dimensional spatial region)
subClass(c45, c42)
class(c46, ns2:three-dimensional spatial region)
subClass(c46, c42)
class(c47, ns2:continuant fiat boundary)
subClass(c47, c40)
class(c48, ns2:fiat line)
subClass(c48, c47)
class(c49, ns2:fiat point)
subClass(c49, c47)
class(c50, ns2:fiat surface)
subClass(c50, c47)
class(c51, ns2:specifically dependent continuant)
subClass(c51, c3)
class(c52, ns2:quality)
subClass(c52, c51)
class(c53, ns2:relational quality)
subClass(c53, c52)
class(c54, ns2:realizable entity)
subClass(c54, c51)
class(c55, ns2:role)
subClass(c55, c54)
class(c56, ns2:agent role)
subClass(c56, c55)
class(c57, ns2:buyer role)
subClass(c57, c56)
class(c58, ns2:supplier role)
subClass(c58, c56)
class(c59, ns2:customer role)
subClass(c59, c56)
class(c60, ns2:manufacturer role)
subClass(c60, c56)
class(c61, ns2:maintainable material item role)
subClass(c61, c55)
class(c62, ns2:material component role)
subClass(c62, c55)
class(c63, ns2:material product role)
subClass(c63, c55)
class(c64, ns2:material resource role)
subClass(c64, c55)
class(c65, ns2:raw material role)
subClass(c65, c55)
class(c66, ns2:disposition)
subClass(c66, c54)
class(c67, ns2:capability)
subClass(c67, c66)
class(c68, ns2:function)
subClass(c68, c66)
class(c69, ns2:occurrent)
subClass(c69, c2)
class(c70, ns2:event)
subClass(c70, c69)
class(c71, ns2:process characteristic)
subClass(c71, c69)
class(c72, ns2:process)
subClass(c72, c69)
class(c73, ns2:planned process)
subClass(c73, c72)
class(c74, ns2:manufacturing process)
subClass(c74, c73)
class(c75, ns2:assembly process)
subClass(c75, c74)
class(c76, ns2:business process)
subClass(c76, c73)
class(c77, ns2:buying business process)
subClass(c77, c76)
class(c78, ns2:commercial service)
subClass(c78, c76)
class(c79, ns2:supplying business process)
subClass(c79, c76)
class(c80, ns2:product production process)
subClass(c80, c76)
class(c81, ns2:offering for sale business process)
subClass(c81, c76)
class(c82, ns2:procuring business process)
subClass(c82, c76)
class(c83, ns2:computing process)
subClass(c83, c73)
class(c84, ns2:material location change process)
subClass(c84, c73)
class(c85, ns2:measurement process)
subClass(c85, c73)
class(c86, ns2:state)
subClass(c86, c72)
class(c87, ns2:history)
subClass(c87, c72)
class(c88, ns2:process boundary)
subClass(c88, c69)
class(c89, ns2:temporal region)
subClass(c89, c69)
class(c90, ns2:one-dimensional temporal region)
subClass(c90, c89)
class(c91, ns2:temporal interval)
subClass(c91, c90)
class(c92, ns2:zero-dimensional temporal region)
subClass(c92, c89)
class(c93, ns2:temporal instant)
subClass(c93, c92)
class(c94, ns2:spatiotemporal region)
subClass(c94, c69)
@enduml