@startuml
!include /Users/pnc12/Documents/GitHub/nowl/nowl/profiles/iof.iuml
left to right direction
title BFO_0000001
class(c1, ns2:entity)
class(c2, ns2:continuant)
subClass(c2, c1)
class(c3, ns2:generically dependent continuant)
subClass(c3, c2)
class(c4, ns2:information content entity)
subClass(c4, c3)
class(c5, ns2:action specification)
subClass(c5, c4)
class(c6, ns2:plan specification)
subClass(c6, c4)
class(c7, ns2:algorithm)
subClass(c7, c6)
class(c8, ns2:commercial service specification)
subClass(c8, c6)
class(c9, ns2:business identification)
subClass(c9, c4)
class(c10, ns2:objective specification)
subClass(c10, c4)
class(c11, ns2:commercial service agreement)
subClass(c11, c4)
class(c12, ns2:descriptive information content entity)
subClass(c12, c4)
class(c13, ns2:design specification)
subClass(c13, c4)
class(c14, ns2:designative information content entity)
subClass(c14, c4)
class(c15, ns2:directive information content entity)
subClass(c15, c4)
class(c16, ns2:location identification)
subClass(c16, c4)
class(c17, ns2:measurement information content entity)
subClass(c17, c4)
class(c18, ns2:requirement specification)
subClass(c18, c4)
class(c19, ns2:information content entity)
subClass(c19, c3)
class(c20, mllo:configuration variable)
subClass(c20, c19)
class(c21, mllo:algorithm verbosity)
subClass(c21, c20)
class(c22, mllo:hyperparameter)
subClass(c22, c20)
class(c23, mllo:batch size)
subClass(c23, c22)
class(c24, mllo:epoch number)
subClass(c24, c22)
class(c25, mllo:machine learning parameter)
subClass(c25, c20)
class(c26, mllo:regression parameter)
subClass(c26, c25)
class(c27, mllo:regression coefficient)
subClass(c27, c26)
class(c28, mllo:regression intercept)
subClass(c28, c26)
class(c29, mllo:statistically significant parameter)
subClass(c29, c25)
class(c30, ns2:data item)
subClass(c30, c19)
class(c31, mllo:target variable)
subClass(c31, c30)
class(c32, mllo:feature)
subClass(c32, c30)
class(c33, mllo:categorical feature)
subClass(c33, c32)
class(c34, mllo:nominal feature)
subClass(c34, c33)
class(c35, mllo:ordinal feature)
subClass(c35, c33)
class(c36, mllo:numerical feature)
subClass(c36, c32)
class(c37, mllo:complex number feature)
subClass(c37, c36)
class(c38, mllo:continuous numeric feature)
subClass(c38, c36)
class(c39, mllo:discrete numeric feature)
subClass(c39, c36)
class(c40, mllo:date-time feature)
subClass(c40, c32)
class(c41, mllo:derived feature)
subClass(c41, c32)
class(c42, mllo:polynomial feature)
subClass(c42, c41)
class(c43, mllo:graph feature)
subClass(c43, c32)
class(c44, mllo:image feature)
subClass(c44, c32)
class(c45, ns2:value expression)
subClass(c45, c30)
class(c46, mllo:simulated value expression)
subClass(c46, c45)
class(c47, mllo:specified value expression)
subClass(c47, c45)
class(c48, ns2:measured value expression)
subClass(c48, c45)
class(c49, ns2:temporal instant value expression)
subClass(c49, c45)
class(c50, mllo:digital image)
subClass(c50, c30)
class(c51, mllo:model output)
subClass(c51, c30)
class(c52, ns2:data set)
subClass(c52, c19)
class(c53, mllo:feature vector)
subClass(c53, c52)
class(c54, mllo:preprocessed data set)
subClass(c54, c52)
class(c55, mllo:feature column)
subClass(c55, c52)
class(c56, mllo:machine learning data set)
subClass(c56, c52)
class(c57, mllo:training data set)
subClass(c57, c56)
class(c58, mllo:test data set)
subClass(c58, c56)
class(c59, mllo:validation data set)
subClass(c59, c56)
class(c60, mllo:production machine learning data set)
subClass(c60, c56)
class(c61, mllo:raw data set)
subClass(c61, c52)
class(c62, mllo:model output data set)
subClass(c62, c52)
class(c63, mllo:target variable vector)
subClass(c63, c52)
class(c64, mllo:configuration variable setting)
subClass(c64, c19)
class(c65, mllo:default setting)
subClass(c65, c64)
class(c66, mllo:machine learning parameter setting)
subClass(c66, c64)
class(c67, mllo:initial machine learning parameter setting)
subClass(c67, c66)
class(c68, mllo:information content entity characteristic)
subClass(c68, c19)
class(c69, mllo:algorithm characteristic)
subClass(c69, c68)
class(c70, mllo:data item characteristic)
subClass(c70, c68)
class(c71, mllo:feature characteristic)
subClass(c71, c70)
class(c72, mllo:data set characteristic)
subClass(c72, c68)
class(c73, mllo:feature vector characteristic)
subClass(c73, c72)
class(c74, mllo:encoded algorithm characteristic)
subClass(c74, c68)
class(c75, mllo:model characteristic)
subClass(c75, c74)
class(c76, mllo:index)
subClass(c76, c19)
class(c77, ns2:programming language)
subClass(c77, c19)
class(c78, ns2:data format specification)
subClass(c78, c19)
class(c79, ns2:probability distribution)
subClass(c79, c19)
class(c80, ns2:prior probability distribution)
subClass(c80, c79)
class(c81, mllo:mathematical function)
subClass(c81, c19)
class(c82, mllo:activation function)
subClass(c82, c81)
class(c83, mllo:rectified linear unit)
subClass(c83, c82)
class(c84, mllo:softmax)
subClass(c84, c82)
class(c85, mllo:performance metric)
subClass(c85, c81)
class(c86, mllo:classification accuracy)
subClass(c86, c85)
class(c87, mllo:hamming loss)
subClass(c87, c85)
class(c88, mllo:mean absolute error)
subClass(c88, c85)
class(c89, mllo:r squared)
subClass(c89, c85)
class(c90, mllo:root mean squared error)
subClass(c90, c85)
class(c91, mllo:success rate)
subClass(c91, c85)
class(c92, mllo:data quality metric)
subClass(c92, c81)
class(c93, mllo:distance metric)
subClass(c93, c81)
class(c94, mllo:loss function)
subClass(c94, c81)
class(c95, mllo:polynomial function)
subClass(c95, c81)
class(c96, mllo:classification scheme)
subClass(c96, c19)
class(c97, mllo:nominal classification scheme)
subClass(c97, c96)
class(c98, mllo:ordinal classification scheme)
subClass(c98, c96)
class(c99, mllo:machine learning model component)
subClass(c99, c19)
class(c100, mllo:cluster)
subClass(c100, c99)
class(c101, mllo:neuron)
subClass(c101, c99)
class(c102, mllo:configuration variable set)
subClass(c102, c19)
class(c103, mllo:hyperparameter set)
subClass(c103, c102)
class(c104, mllo:machine learning parameter set)
subClass(c104, c102)
class(c105, mllo:information content entity ordering scheme)
subClass(c105, c19)
class(c106, mllo:sequential feature ordering scheme)
subClass(c106, c105)
class(c107, mllo:noise)
subClass(c107, c19)
class(c108, mllo:gaussian noise)
subClass(c108, c107)
class(c109, mllo:poisson noise)
subClass(c109, c107)
class(c110, mllo:graph)
subClass(c110, c19)
class(c111, mllo:group of machine learning models)
subClass(c111, c19)
class(c112, mllo:machine learning framework)
subClass(c112, c19)
class(c113, mllo:keras)
subClass(c113, c112)
class(c114, mllo:tensorflow)
subClass(c114, c112)
class(c115, mllo:model performance result)
subClass(c115, c19)
class(c116, ns2:algorithm)
subClass(c116, c19)
class(c117, mllo:optimization algorithm)
subClass(c117, c116)
class(c118, mllo:adam optimizer)
subClass(c118, c117)
class(c119, mllo:machine learning training algorithm)
subClass(c119, c116)
class(c120, mllo:artificial neural network training algorithm)
subClass(c120, c119)
class(c121, mllo:backpropagation)
subClass(c121, c120)
class(c122, mllo:association rule learning algorithm)
subClass(c122, c119)
class(c123, mllo:bayesian algorithm)
subClass(c123, c119)
class(c124, mllo:clustering algorithm)
subClass(c124, c119)
class(c125, mllo:decision tree algorithm)
subClass(c125, c119)
class(c126, mllo:dimensionality reduction algorithm)
subClass(c126, c119)
class(c127, mllo:ensemble algorithm)
subClass(c127, c119)
class(c128, mllo:instance-based algorithm)
subClass(c128, c119)
class(c129, mllo:polynomial model training algorithm)
subClass(c129, c119)
class(c130, mllo:data processing algorithm)
subClass(c130, c116)
class(c131, mllo:data cleaning algorithm)
subClass(c131, c130)
class(c132, mllo:data imputation algorithm)
subClass(c132, c131)
class(c133, mllo:feature engineering algorithm)
subClass(c133, c130)
class(c134, mllo:feature scaling algorithm)
subClass(c134, c133)
class(c135, mllo:initialization algorithm)
subClass(c135, c116)
class(c136, mllo:regularization method)
subClass(c136, c116)
class(c137, mllo:machine learning model algorithm)
subClass(c137, c116)
class(c138, mllo:model output transformation algorithm)
subClass(c138, c116)
subClass(c45, c19)
class(c139, ns2:objective specification)
subClass(c139, c19)
class(c140, mllo:model execution objective)
subClass(c140, c139)
class(c141, mllo:action selection objective)
subClass(c141, c140)
class(c142, mllo:prediction objective)
subClass(c142, c140)
class(c143, mllo:classification objective)
subClass(c143, c142)
class(c144, mllo:regression objective)
subClass(c144, c142)
class(c145, mllo:data description objective)
subClass(c145, c140)
class(c146, mllo:data cleaning objective)
subClass(c146, c139)
class(c147, ns2:output objective specification)
subClass(c147, c139)
class(c148, ns2:identifier)
subClass(c148, c19)
class(c149, ns2:organization identifier)
subClass(c149, c148)
class(c150, ns2:physical location identifier)
subClass(c150, c148)
class(c151, ns2:requirement specification)
subClass(c151, c19)
class(c152, mllo:model input requirements)
subClass(c152, c151)
class(c153, mllo:model assumptions)
subClass(c153, c152)
class(c154, mllo:statistical significance criteria)
subClass(c154, c151)
class(c155, ns2:directive information content entity)
subClass(c155, c19)
class(c156, ns2:action specification)
subClass(c156, c19)
class(c157, ns2:plan specification)
subClass(c157, c19)
class(c158, ns2:encoded algorithm)
subClass(c158, c157)
class(c159, mllo:machine learning model)
subClass(c159, c158)
class(c160, mllo:artificial neural network)
subClass(c160, c159)
class(c161, mllo:convolutional neural network)
subClass(c161, c160)
class(c162, mllo:multi layer perceptron)
subClass(c162, c160)
class(c163, mllo:association rule model)
subClass(c163, c159)
class(c164, mllo:clustering model)
subClass(c164, c159)
class(c165, mllo:non-parametric model)
subClass(c165, c159)
class(c166, mllo:decision tree model)
subClass(c166, c165)
class(c167, mllo:gaussian process regression)
subClass(c167, c165)
class(c168, mllo:instance-based model)
subClass(c168, c165)
class(c169, mllo:support vector machine)
subClass(c169, c168)
class(c170, mllo:dimensionality reduction model)
subClass(c170, c159)
class(c171, mllo:polynomial model)
subClass(c171, c159)
class(c172, mllo:linear model)
subClass(c172, c171)
class(c173, mllo:logistic regression)
subClass(c173, c171)
class(c174, mllo:encoded data cleaning algorithm)
subClass(c174, c158)
class(c175, mllo:encoded feature engineering algorithm)
subClass(c175, c158)
class(c176, mllo:encoded initialization algorithm)
subClass(c176, c158)
class(c177, mllo:encoded machine learning training algorithm)
subClass(c177, c158)
class(c178, mllo:encoded optimization algorithm)
subClass(c178, c158)
class(c179, mllo:encoded regularization method)
subClass(c179, c158)
class(c180, ns2:commercial service specification)
subClass(c180, c157)
class(c181, ns2:agreement)
subClass(c181, c19)
class(c182, ns2:commercial service agreement)
subClass(c182, c181)
class(c183, ns2:input specification)
subClass(c183, c19)
class(c184, ns2:descriptive information content entity)
subClass(c184, c19)
class(c185, ns2:design specification)
subClass(c185, c19)
class(c186, ns2:designative information content entity)
subClass(c186, c19)
class(c187, ns2:measurement information content entity)
subClass(c187, c19)
class(c188, ns2:independent continuant)
subClass(c188, c2)
class(c189, ns2:material entity)
subClass(c189, c188)
class(c190, ns2:agent)
subClass(c190, c189)
class(c191, ns2:material component)
subClass(c191, c189)
class(c192, ns2:material product)
subClass(c192, c189)
class(c193, ns2:maintainable material item)
subClass(c193, c189)
class(c194, ns2:material resource)
subClass(c194, c189)
class(c195, ns2:raw material)
subClass(c195, c189)
class(c196, ns2:fiat object part)
subClass(c196, c189)
class(c197, ns2:object aggregate)
subClass(c197, c189)
class(c198, ns2:group of agents)
subClass(c198, c197)
class(c199, ns2:organized group of agents)
subClass(c199, c198)
class(c200, ns2:business organization)
subClass(c200, c199)
class(c201, ns2:system)
subClass(c201, c197)
class(c202, ns2:engineered system)
subClass(c202, c201)
class(c203, ns2:group of agents)
subClass(c203, c197)
class(c204, ns2:organized group of agents)
subClass(c204, c203)
class(c205, ns2:organization)
subClass(c205, c204)
class(c206, ns2:business organization)
subClass(c206, c205)
class(c207, ns2:system)
subClass(c207, c197)
class(c208, ns2:engineered system)
subClass(c208, c207)
class(c209, ns2:group of persons)
subClass(c209, c197)
class(c210, ns2:object)
subClass(c210, c189)
class(c211, ns2:person)
subClass(c211, c210)
class(c212, ns2:material artifact)
subClass(c212, c210)
class(c213, ns2:assembly)
subClass(c213, c212)
class(c214, ns2:machine)
subClass(c214, c212)
class(c215, ns2:person)
subClass(c215, c210)
class(c216, ns2:material artifact)
subClass(c216, c210)
class(c217, ns2:assembly)
subClass(c217, c216)
class(c218, ns2:agent)
subClass(c218, c189)
class(c219, ns2:buyer)
subClass(c219, c218)
class(c220, ns2:customer)
subClass(c220, c218)
class(c221, ns2:manufacturer)
subClass(c221, c218)
class(c222, ns2:supplier)
subClass(c222, c218)
class(c223, ns2:service provider)
subClass(c223, c222)
class(c224, ns2:material component)
subClass(c224, c189)
class(c225, ns2:material product)
subClass(c225, c189)
class(c226, ns2:consumable)
subClass(c226, c189)
class(c227, ns2:maintainable material item)
subClass(c227, c189)
class(c228, ns2:material resource)
subClass(c228, c189)
class(c229, ns2:piece of equipment)
subClass(c229, c189)
class(c230, ns2:raw material)
subClass(c230, c189)
class(c231, ns2:immaterial entity)
subClass(c231, c188)
class(c232, ns2:site)
subClass(c232, c231)
class(c233, ns2:spatial region)
subClass(c233, c231)
class(c234, ns2:two-dimensional spatial region)
subClass(c234, c233)
class(c235, ns2:zero-dimensional spatial region)
subClass(c235, c233)
class(c236, ns2:one-dimensional spatial region)
subClass(c236, c233)
class(c237, ns2:three-dimensional spatial region)
subClass(c237, c233)
class(c238, ns2:continuant fiat boundary)
subClass(c238, c231)
class(c239, ns2:fiat line)
subClass(c239, c238)
class(c240, ns2:fiat point)
subClass(c240, c238)
class(c241, ns2:fiat surface)
subClass(c241, c238)
class(c242, ns2:specifically dependent continuant)
subClass(c242, c2)
class(c243, ns2:quality)
subClass(c243, c242)
class(c244, ns2:relational quality)
subClass(c244, c243)
class(c245, ns2:realizable entity)
subClass(c245, c242)
class(c246, ns2:role)
subClass(c246, c245)
class(c247, ns2:agent role)
subClass(c247, c246)
class(c248, ns2:buyer role)
subClass(c248, c247)
class(c249, ns2:supplier role)
subClass(c249, c247)
class(c250, ns2:customer role)
subClass(c250, c247)
class(c251, ns2:manufacturer role)
subClass(c251, c247)
class(c252, ns2:maintainable material item role)
subClass(c252, c246)
class(c253, ns2:material component role)
subClass(c253, c246)
class(c254, ns2:material product role)
subClass(c254, c246)
class(c255, ns2:material resource role)
subClass(c255, c246)
class(c256, ns2:raw material role)
subClass(c256, c246)
class(c257, ns2:agent role)
subClass(c257, c246)
class(c258, ns2:buyer role)
subClass(c258, c257)
class(c259, ns2:customer role)
subClass(c259, c257)
class(c260, ns2:manufacturer role)
subClass(c260, c257)
class(c261, ns2:supplier role)
subClass(c261, c257)
class(c262, ns2:service provider role)
subClass(c262, c261)
class(c263, ns2:consumable role)
subClass(c263, c246)
class(c264, ns2:equipment role)
subClass(c264, c246)
class(c265, ns2:maintainable material item role)
subClass(c265, c246)
class(c266, ns2:material component role)
subClass(c266, c246)
class(c267, ns2:material product role)
subClass(c267, c246)
class(c268, ns2:material resource role)
subClass(c268, c246)
class(c269, ns2:raw material role)
subClass(c269, c246)
class(c270, ns2:disposition)
subClass(c270, c245)
class(c271, ns2:capability)
subClass(c271, c270)
class(c272, ns2:function)
subClass(c272, c270)
class(c273, ns2:business function)
subClass(c273, c272)
class(c274, ns2:designed function)
subClass(c274, c272)
class(c275, ns2:capability)
subClass(c275, c270)
subClass(c272, c275)
class(c276, ns2:measurement capability)
subClass(c276, c275)
class(c277, ns2:process characteristic)
subClass(c277, c2)
class(c278, ns2:occurrent)
subClass(c278, c1)
class(c279, ns2:event)
subClass(c279, c278)
class(c280, ns2:process characteristic)
subClass(c280, c278)
class(c281, ns2:process)
subClass(c281, c278)
class(c282, ns2:planned process)
subClass(c282, c281)
class(c283, ns2:manufacturing process)
subClass(c283, c282)
class(c284, ns2:assembly process)
subClass(c284, c283)
class(c285, ns2:business process)
subClass(c285, c282)
class(c286, ns2:buying business process)
subClass(c286, c285)
class(c287, ns2:commercial service)
subClass(c287, c285)
class(c288, ns2:supplying business process)
subClass(c288, c285)
class(c289, ns2:product production process)
subClass(c289, c285)
class(c290, ns2:offering for sale business process)
subClass(c290, c285)
class(c291, ns2:procuring business process)
subClass(c291, c285)
class(c292, ns2:computing process)
subClass(c292, c282)
class(c293, ns2:material location change process)
subClass(c293, c282)
class(c294, ns2:measurement process)
subClass(c294, c282)
class(c295, ns2:state)
subClass(c295, c281)
class(c296, ns2:history)
subClass(c296, c281)
class(c297, mllo:deployed machine learning model state)
subClass(c297, c281)
class(c298, ns2:planned process)
subClass(c298, c281)
class(c299, mllo:data quality assesment)
subClass(c299, c298)
class(c300, mllo:data quality monitoring)
subClass(c300, c298)
class(c301, mllo:machine learning model deployment process)
subClass(c301, c298)
class(c302, mllo:exploratory data analysis)
subClass(c302, c298)
class(c303, mllo:feature selection)
subClass(c303, c298)
class(c304, mllo:hyperparameter tuning)
subClass(c304, c298)
class(c305, mllo:model validation)
subClass(c305, c298)
class(c306, mllo:machine learning data set partitioning)
subClass(c306, c298)
class(c307, mllo:machine learning model development pipeline)
subClass(c307, c298)
class(c308, mllo:model performance assessment)
subClass(c308, c298)
class(c309, mllo:model evaluation)
subClass(c309, c308)
class(c310, mllo:model performance monitoring)
subClass(c310, c298)
class(c311, mllo:model selection)
subClass(c311, c298)
class(c312, ns2:computing process)
subClass(c312, c298)
class(c313, mllo:machine learning training)
subClass(c313, c312)
class(c314, mllo:machine learning model update)
subClass(c314, c313)
class(c315, mllo:reinforcement learning)
subClass(c315, c313)
class(c316, mllo:semi supervised learning)
subClass(c316, c313)
class(c317, mllo:supervised learning)
subClass(c317, c313)
class(c318, mllo:unsupervised learning)
subClass(c318, c313)
class(c319, mllo:data processing operation)
subClass(c319, c312)
class(c320, mllo:data cleaning operation)
subClass(c320, c319)
class(c321, mllo:data imputation operation)
subClass(c321, c320)
class(c322, mllo:data reshaping operation)
subClass(c322, c319)
class(c323, mllo:feature engineering operation)
subClass(c323, c319)
class(c324, mllo:feature decomposition)
subClass(c324, c323)
class(c325, mllo:feature engineering transformation)
subClass(c325, c323)
class(c326, mllo:feature scaling operation)
subClass(c326, c325)
class(c327, mllo:feature generation)
subClass(c327, c323)
class(c328, mllo:model output transformation operation)
subClass(c328, c319)
class(c329, mllo:one hot encoding)
subClass(c329, c319)
class(c330, mllo:type casting operation)
subClass(c330, c319)
class(c331, mllo:data processing pipeline)
subClass(c331, c312)
class(c332, mllo:data cleaning pipeline)
subClass(c332, c331)
class(c333, mllo:feature engineering pipeline)
subClass(c333, c331)
class(c334, mllo:machine learning data preparation pipeline)
subClass(c334, c331)
class(c335, mllo:machine learning parameter initialization)
subClass(c335, c312)
class(c336, mllo:model execution)
subClass(c336, c312)
class(c337, ns2:manufacturing process)
subClass(c337, c298)
class(c338, ns2:assembly process)
subClass(c338, c337)
class(c339, ns2:business process)
subClass(c339, c298)
class(c340, ns2:buying business process)
subClass(c340, c339)
class(c341, ns2:commercial service)
subClass(c341, c339)
class(c342, ns2:supplying business process)
subClass(c342, c339)
class(c343, ns2:product production process)
subClass(c343, c339)
class(c344, ns2:offering for sale business process)
subClass(c344, c339)
class(c345, ns2:procuring business process)
subClass(c345, c339)
class(c346, ns2:material location change process)
subClass(c346, c298)
class(c347, ns2:measurement process)
subClass(c347, c298)
class(c348, ns2:process profile)
subClass(c348, c281)
class(c349, ns2:gain of role)
subClass(c349, c281)
class(c350, ns2:loss of role)
subClass(c350, c281)
class(c351, ns2:material state)
subClass(c351, c281)
class(c352, ns2:process boundary)
subClass(c352, c278)
class(c353, ns2:temporal region)
subClass(c353, c278)
class(c354, ns2:one-dimensional temporal region)
subClass(c354, c353)
class(c355, ns2:temporal interval)
subClass(c355, c354)
class(c356, mllo:epoch)
subClass(c356, c355)
class(c357, ns2:zero-dimensional temporal region)
subClass(c357, c353)
class(c358, ns2:temporal instant)
subClass(c358, c357)
class(c359, ns2:spatiotemporal region)
subClass(c359, c278)
class(c360, ns2:event)
subClass(c360, c278)
@enduml