@startuml
!include /Users/pnc12/Documents/GitHub/nowl/nowl/profiles/iof.iuml
left to right direction
title InformationContentEntity_InformationContentEntity
class(c1, ns2:information content entity)
class(c2, ns2:action specification)
subClass(c2, c1)
class(c3, ns2:agreement)
subClass(c3, c1)
class(c4, ns2:commercial service agreement)
subClass(c4, c3)
class(c5, ns2:objective specification)
subClass(c5, c1)
class(c6, ns2:output objective specification)
subClass(c6, c5)
class(c7, ns2:algorithm)
subClass(c7, c1)
class(c8, ns2:plan specification)
subClass(c8, c1)
class(c9, ns2:commercial service specification)
subClass(c9, c8)
class(c10, ns2:encoded algorithm)
subClass(c10, c8)
class(c11, ns2:input specification)
subClass(c11, c1)
class(c12, ns2:descriptive information content entity)
subClass(c12, c1)
class(c13, ns2:design specification)
subClass(c13, c1)
class(c14, ns2:designative information content entity)
subClass(c14, c1)
class(c15, ns2:directive information content entity)
subClass(c15, c1)
class(c16, ns2:identifier)
subClass(c16, c1)
class(c17, ns2:organization identifier)
subClass(c17, c16)
class(c18, ns2:physical location identifier)
subClass(c18, c16)
class(c19, ns2:value expression)
subClass(c19, c1)
class(c20, ns2:measured value expression)
subClass(c20, c19)
class(c21, ns2:temporal instant value expression)
subClass(c21, c19)
class(c22, ns2:measurement information content entity)
subClass(c22, c1)
class(c23, ns2:requirement specification)
subClass(c23, c1)
class(c24, iof:information content entity)
class(c25, mllo:configuration variable)
subClass(c25, c24)
class(c26, mllo:algorithm verbosity)
subClass(c26, c25)
class(c27, mllo:hyperparameter)
subClass(c27, c25)
class(c28, mllo:batch size)
subClass(c28, c27)
class(c29, mllo:epoch number)
subClass(c29, c27)
class(c30, mllo:machine learning parameter)
subClass(c30, c25)
class(c31, mllo:regression parameter)
subClass(c31, c30)
class(c32, mllo:regression coefficient)
subClass(c32, c31)
class(c33, mllo:regression intercept)
subClass(c33, c31)
class(c34, mllo:statistically significant parameter)
subClass(c34, c30)
class(c35, ns2:data item)
subClass(c35, c24)
class(c36, mllo:target variable)
subClass(c36, c35)
class(c37, mllo:feature)
subClass(c37, c35)
class(c38, mllo:categorical feature)
subClass(c38, c37)
class(c39, mllo:nominal feature)
subClass(c39, c38)
class(c40, mllo:ordinal feature)
subClass(c40, c38)
class(c41, mllo:numerical feature)
subClass(c41, c37)
class(c42, mllo:complex number feature)
subClass(c42, c41)
class(c43, mllo:continuous numeric feature)
subClass(c43, c41)
class(c44, mllo:discrete numeric feature)
subClass(c44, c41)
class(c45, mllo:date-time feature)
subClass(c45, c37)
class(c46, mllo:derived feature)
subClass(c46, c37)
class(c47, mllo:polynomial feature)
subClass(c47, c46)
class(c48, mllo:graph feature)
subClass(c48, c37)
class(c49, mllo:image feature)
subClass(c49, c37)
class(c50, iof:value expression)
subClass(c50, c35)
class(c51, mllo:simulated value expression)
subClass(c51, c50)
class(c52, mllo:specified value expression)
subClass(c52, c50)
class(c53, iof:measured value expression)
subClass(c53, c50)
class(c54, iof:temporal interval value expression)
subClass(c54, c50)
class(c55, iof:temporal instant value expression)
subClass(c55, c50)
class(c56, mllo:digital image)
subClass(c56, c35)
class(c57, mllo:model output)
subClass(c57, c35)
class(c58, ns2:data set)
subClass(c58, c24)
class(c59, mllo:feature vector)
subClass(c59, c58)
class(c60, mllo:preprocessed data set)
subClass(c60, c58)
class(c61, mllo:feature column)
subClass(c61, c58)
class(c62, mllo:machine learning data set)
subClass(c62, c58)
class(c63, mllo:training data set)
subClass(c63, c62)
class(c64, mllo:test data set)
subClass(c64, c62)
class(c65, mllo:validation data set)
subClass(c65, c62)
class(c66, mllo:production machine learning data set)
subClass(c66, c62)
class(c67, mllo:raw data set)
subClass(c67, c58)
class(c68, mllo:model output data set)
subClass(c68, c58)
class(c69, mllo:target variable vector)
subClass(c69, c58)
class(c70, mllo:configuration variable setting)
subClass(c70, c24)
class(c71, mllo:default setting)
subClass(c71, c70)
class(c72, mllo:machine learning parameter setting)
subClass(c72, c70)
class(c73, mllo:initial machine learning parameter setting)
subClass(c73, c72)
class(c74, mllo:information content entity characteristic)
subClass(c74, c24)
class(c75, mllo:algorithm characteristic)
subClass(c75, c74)
class(c76, mllo:data item characteristic)
subClass(c76, c74)
class(c77, mllo:feature characteristic)
subClass(c77, c76)
class(c78, mllo:data set characteristic)
subClass(c78, c74)
class(c79, mllo:feature vector characteristic)
subClass(c79, c78)
class(c80, mllo:encoded algorithm characteristic)
subClass(c80, c74)
class(c81, mllo:model characteristic)
subClass(c81, c80)
class(c82, mllo:index)
subClass(c82, c24)
class(c83, ns2:programming language)
subClass(c83, c24)
class(c84, ns2:data format specification)
subClass(c84, c24)
class(c85, ns2:probability distribution)
subClass(c85, c24)
class(c86, ns2:prior probability distribution)
subClass(c86, c85)
class(c87, mllo:mathematical function)
subClass(c87, c24)
class(c88, mllo:activation function)
subClass(c88, c87)
class(c89, mllo:rectified linear unit)
subClass(c89, c88)
class(c90, mllo:softmax)
subClass(c90, c88)
class(c91, mllo:performance metric)
subClass(c91, c87)
class(c92, mllo:classification accuracy)
subClass(c92, c91)
class(c93, mllo:hamming loss)
subClass(c93, c91)
class(c94, mllo:mean absolute error)
subClass(c94, c91)
class(c95, mllo:r squared)
subClass(c95, c91)
class(c96, mllo:root mean squared error)
subClass(c96, c91)
class(c97, mllo:success rate)
subClass(c97, c91)
class(c98, mllo:data quality metric)
subClass(c98, c87)
class(c99, mllo:distance metric)
subClass(c99, c87)
class(c100, mllo:loss function)
subClass(c100, c87)
class(c101, mllo:polynomial function)
subClass(c101, c87)
class(c102, mllo:classification scheme)
subClass(c102, c24)
class(c103, mllo:nominal classification scheme)
subClass(c103, c102)
class(c104, mllo:ordinal classification scheme)
subClass(c104, c102)
class(c105, mllo:machine learning model component)
subClass(c105, c24)
class(c106, mllo:cluster)
subClass(c106, c105)
class(c107, mllo:neuron)
subClass(c107, c105)
class(c108, mllo:configuration variable set)
subClass(c108, c24)
class(c109, mllo:hyperparameter set)
subClass(c109, c108)
class(c110, mllo:machine learning parameter set)
subClass(c110, c108)
class(c111, mllo:information content entity ordering scheme)
subClass(c111, c24)
class(c112, mllo:sequential feature ordering scheme)
subClass(c112, c111)
class(c113, mllo:noise)
subClass(c113, c24)
class(c114, mllo:gaussian noise)
subClass(c114, c113)
class(c115, mllo:poisson noise)
subClass(c115, c113)
class(c116, mllo:graph)
subClass(c116, c24)
class(c117, mllo:group of machine learning models)
subClass(c117, c24)
class(c118, mllo:machine learning framework)
subClass(c118, c24)
class(c119, mllo:keras)
subClass(c119, c118)
class(c120, mllo:tensorflow)
subClass(c120, c118)
class(c121, mllo:model performance result)
subClass(c121, c24)
class(c122, iof:algorithm)
subClass(c122, c24)
class(c123, mllo:optimization algorithm)
subClass(c123, c122)
class(c124, mllo:adam optimizer)
subClass(c124, c123)
class(c125, mllo:machine learning training algorithm)
subClass(c125, c122)
class(c126, mllo:artificial neural network training algorithm)
subClass(c126, c125)
class(c127, mllo:backpropagation)
subClass(c127, c126)
class(c128, mllo:association rule learning algorithm)
subClass(c128, c125)
class(c129, mllo:bayesian algorithm)
subClass(c129, c125)
class(c130, mllo:clustering algorithm)
subClass(c130, c125)
class(c131, mllo:decision tree algorithm)
subClass(c131, c125)
class(c132, mllo:dimensionality reduction algorithm)
subClass(c132, c125)
class(c133, mllo:ensemble algorithm)
subClass(c133, c125)
class(c134, mllo:instance-based algorithm)
subClass(c134, c125)
class(c135, mllo:polynomial model training algorithm)
subClass(c135, c125)
class(c136, mllo:data processing algorithm)
subClass(c136, c122)
class(c137, mllo:data cleaning algorithm)
subClass(c137, c136)
class(c138, mllo:data imputation algorithm)
subClass(c138, c137)
class(c139, mllo:feature engineering algorithm)
subClass(c139, c136)
class(c140, mllo:feature scaling algorithm)
subClass(c140, c139)
class(c141, mllo:initialization algorithm)
subClass(c141, c122)
class(c142, mllo:regularization method)
subClass(c142, c122)
class(c143, mllo:machine learning model algorithm)
subClass(c143, c122)
class(c144, mllo:model output transformation algorithm)
subClass(c144, c122)
subClass(c50, c24)
class(c145, iof:objective specification)
subClass(c145, c24)
class(c146, mllo:model execution objective)
subClass(c146, c145)
class(c147, mllo:action selection objective)
subClass(c147, c146)
class(c148, mllo:prediction objective)
subClass(c148, c146)
class(c149, mllo:classification objective)
subClass(c149, c148)
class(c150, mllo:regression objective)
subClass(c150, c148)
class(c151, mllo:data description objective)
subClass(c151, c146)
class(c152, mllo:data cleaning objective)
subClass(c152, c145)
class(c153, iof:identifier)
subClass(c153, c24)
class(c154, iof:organization identifier)
subClass(c154, c153)
class(c155, iof:physical location identifier)
subClass(c155, c153)
class(c156, iof:requirement specification)
subClass(c156, c24)
class(c157, mllo:model input requirements)
subClass(c157, c156)
class(c158, mllo:model assumptions)
subClass(c158, c157)
class(c159, mllo:statistical significance criteria)
subClass(c159, c156)
class(c160, iof:directive information content entity)
subClass(c160, c24)
class(c161, iof:action specification)
subClass(c161, c24)
class(c162, iof:plan specification)
subClass(c162, c24)
class(c163, iof:encoded algorithm)
subClass(c163, c162)
class(c164, mllo:machine learning model)
subClass(c164, c163)
class(c165, mllo:artificial neural network)
subClass(c165, c164)
class(c166, mllo:convolutional neural network)
subClass(c166, c165)
class(c167, mllo:multi layer perceptron)
subClass(c167, c165)
class(c168, mllo:association rule model)
subClass(c168, c164)
class(c169, mllo:clustering model)
subClass(c169, c164)
class(c170, mllo:non-parametric model)
subClass(c170, c164)
class(c171, mllo:decision tree model)
subClass(c171, c170)
class(c172, mllo:gaussian process regression)
subClass(c172, c170)
class(c173, mllo:instance-based model)
subClass(c173, c170)
class(c174, mllo:support vector machine)
subClass(c174, c173)
class(c175, mllo:dimensionality reduction model)
subClass(c175, c164)
class(c176, mllo:polynomial model)
subClass(c176, c164)
class(c177, mllo:linear model)
subClass(c177, c176)
class(c178, mllo:logistic regression)
subClass(c178, c176)
class(c179, mllo:encoded data cleaning algorithm)
subClass(c179, c163)
class(c180, mllo:encoded feature engineering algorithm)
subClass(c180, c163)
class(c181, mllo:encoded initialization algorithm)
subClass(c181, c163)
class(c182, mllo:encoded machine learning training algorithm)
subClass(c182, c163)
class(c183, mllo:encoded optimization algorithm)
subClass(c183, c163)
class(c184, mllo:encoded regularization method)
subClass(c184, c163)
class(c185, iof:commercial service specification)
subClass(c185, c162)
class(c186, iof:agreement)
subClass(c186, c24)
class(c187, iof:commercial service agreement)
subClass(c187, c186)
class(c188, iof:descriptive information content entity)
subClass(c188, c24)
class(c189, iof:design specification)
subClass(c189, c24)
class(c190, iof:designative information content entity)
subClass(c190, c24)
class(c191, iof:measurement information content entity)
subClass(c191, c24)
@enduml